# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - main
      - feat/*
  paths:
    exclude:
      - 'service-a/*'
      - 'service-b/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from '/' root folder."
